### ISSUE TITLE
Not Found - org.springframework.boot:spring-boot-starter-tomcat:2.0.0.M2

### ISSUE THREAD

**Issue by gsbindhani** [salmar/spring-websocket-chat#16]
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find spring-boot-starter-tomcat.jar (org.springframework.boot:spring-boot-starter-tomcat:2.0.0.M2).
  Searched in the following locations:
      http://repo.spring.io/libs-release/org/springframework/boot/spring-boot-starter-tomcat/2.0.0.M2/spring-boot-starter-tomcat-2.0.0.M2.jar

**Comment by aminetroudi** [comment]
I had the same problem i changed the SpringBootVersion in build.gradle as follows:
`springBootVersion = '1.5.8.RELEASE'`
then 
`gradle clean`
`gradle bootRun`

**Comment by hri101** [comment]
I had same issue, but fixed in build.gradle:

`    //maven { url "http://repo.spring.io/libs-release" }`
`    maven { url "http://repo.spring.io/plugins-release" }`

This allows to preserve 

`springBootVersion = '2.0.0.M2'`

**Comment by Abnormally** [comment]
Found same problem with 2.0.0.RELEASE
Fixed in build.gradle:

```
dependencies {
// ... //
compile group: 'org.springframework.boot', name: 'spring-boot-starter-tomcat', version: '2.0.0.RELEASE'
// ... //
}
```

P.S.: Great thanks to @salmar for this repository.

**Comment by salmar** [comment]
Upgraded the sample to Spring Boot 2.0.0.RELEASE, `spring-boot-starter-tomcat` is a transient dependency of `spring-boot-starter-web`
