### ISSUE TITLE
Fix the gradle.build

### ISSUE THREAD

**Issue by marrafi** [salmar/spring-websocket-chat#2]
You might want fix the gradle build as follows 
*compile("org.springframework.security:spring-security-messaging:4.0.2.RELEASE")
*springBootVersion = '1.3.0.M3'

**Comment by superjames** [comment]
+1
Thanks !

It removed this error when building:

09:23:23.624 [INFO] [org.gradle.api.Project] Configuring agent
09:23:23.627 [DEBUG] [org.gradle.api.Project] Agent: null
09:23:23.652 [ERROR] [org.gradle.BuildExceptionReporter] 
09:23:23.656 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:23:23.657 [ERROR] [org.gradle.BuildExceptionReporter] 
09:23:23.658 [ERROR] [org.gradle.BuildExceptionReporter] \* Where:
09:23:23.658 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/tmp/spring-websocket-chat/build.gradle' line: 3
09:23:23.659 [ERROR] [org.gradle.BuildExceptionReporter] 
09:23:23.660 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
09:23:23.662 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'spring-websocket-chat'.
09:23:23.663 [ERROR] [org.gradle.BuildExceptionReporter] > org/gradle/mvn3/org/apache/maven/model/building/ModelBuildingException
09:23:23.664 [ERROR] [org.gradle.BuildExceptionReporter] 
09:23:23.664 [ERROR] [org.gradle.BuildExceptionReporter] \* Try:
09:23:23.665 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
09:23:23.666 [LIFECYCLE] [org.gradle.BuildResultLogger] 
09:23:23.667 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
09:23:23.667 [LIFECYCLE] [org.gradle.BuildResultLogger] 
09:23:23.668 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 6.728 secs

**Comment by salmar** [comment]
I've updated the following dependencies:

Spring Boot 1.3.0.M5
Commons Pool 2 2.4.2
Netty 4.0.31.Final
Reactor 2.0.5.RELEASE
Spring Session 1.0.2.RELEASE
