### ISSUE TITLE
Issue while running the bootRun

### ISSUE THREAD

**Issue by sreekanthsnair** [salmar/spring-websocket-chat#4]
Hi Almar,
               Appreciate your real world approach with spring websocket, was trying to run the app but was getting the following error while gradle bootRun. 

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/srikanth/chatapp/spring-websocket-chat/build.gradle' line: 3
- What went wrong:
  A problem occurred evaluating root project 'spring-websocket-chat'.
  
  > org.gradle.api.tasks.TaskContainer.create(Ljava/lang/String;Ljava/lang/Class;)Lorg/gradle/api/Task;
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by salmar** [comment]
What version of Gradle are you using?

**Comment by egov-systems** [comment]
Gradle 1.5
Groovy: 1.8.6
JVM: 1.8.0_31 (Oracle Corporation 25.31-b07)
OS: Linux 3.19.0-22-generic amd64

**Comment by sreekanthsnair** [comment]
Gradle 1.5
Groovy: 1.8.6
JVM: 1.8.0_31 (Oracle Corporation 25.31-b07)
OS: Linux 3.19.0-22-generic amd64

**Comment by salmar** [comment]
Upgrade your Gradle version (current is 2.8) and try to rebuild. See https://stackoverflow.com/questions/22356216/org-gradle-api-internal-locationawareexception-from-gradle

**Comment by sreekanthsnair** [comment]
Thanks almar...
