### ISSUE TITLE
How to save data/messages in database like mysql, maria, postgre or mongo db

### ISSUE THREAD

**Issue by arshadalisoomro** [salmar/spring-websocket-chat#7]
I've forked the repository and found it awesome, but I can not find the way to save data to database like mysql, maria, postgre or mongo db. I've not found any resource online as well, So requesting you please add/tell support for persisting data/messages in database like mysql, maria, postgre or mongo db.

Regards : 
Arshad Ali Soomro.

**Comment by Alejano-Borhez** [comment]
Hello!
In this test study project only in-memory database h2sql is implemented.
Adding a new module implementing SocialDao interface you may create your own implementation using any database you like.

Best regards,
Alexander Borohov

**Comment by salmar** [comment]
The sample doesn't have the option to store messages on a data store, but it could be easily done with a channel interceptor or directly on the `ChatController`
